<h2 align="center"> Creación de un corpus de libros de texto de primaria </h2>

In [1]:
import os

def cargar_corpus(ruta_corpus):
    corpus = []
    grados = sorted([d for d in os.listdir(ruta_corpus) if os.path.isdir(os.path.join(ruta_corpus, d))])
    for grado in grados:
        ruta_grado = os.path.join(ruta_corpus, grado)
        materias = [m for m in os.listdir(ruta_grado) if os.path.isdir(os.path.join(ruta_grado, m))]
        for materia in materias:
            ruta_materia = os.path.join(ruta_grado, materia)
            archivos = [a for a in os.listdir(ruta_materia) if a.endswith(".txt")]
            for archivo in archivos:
                ruta_archivo = os.path.join(ruta_materia, archivo)
                with open(ruta_archivo, "r", encoding="utf-8") as f:
                    contenido = f.read()
                corpus.append({
                    "grado": grado,
                    "materia": materia,
                    "archivo": archivo,
                    "contenido": contenido
                })
    return corpus

# Ejemplo de uso
ruta_corpus = "corpus"
corpus = cargar_corpus(ruta_corpus)

## Transformación y limpieza del corpus (contenido)

In [2]:
# Transformamos el contenido a minúsculas, eliminamos signos como los de puntuación, acentos y números en romanos y demas caracteres especiales
import re
import unicodedata

for texto in corpus:
    # Saltos de línea
    texto["contenido"] = texto["contenido"].replace("\n", " ").replace("\r", " ")
    # Palabra "words"
    texto["contenido"] = texto["contenido"].replace("words", "")
    # Minúsculas
    texto["contenido"] = texto["contenido"].lower()
    # Signos de puntuación
    texto["contenido"] = re.sub(r"[^\w\s]", "", texto["contenido"])
    # Acentos
    texto["contenido"] = unicodedata.normalize("NFKD", texto["contenido"]).encode("ascii", "ignore").decode("utf-8")
    # Números
    texto["contenido"] = re.sub(r"\b\d+\b", "", texto["contenido"])
    # Números romanos
    texto["contenido"] = re.sub(r"\b[ivxlcdm]+\b", "", texto["contenido"])
    # Caracteres especiales
    texto["contenido"] = re.sub(r"[^a-zñ\s]", "", texto["contenido"])
    # Espacios múltiples
    texto["contenido"] = re.sub(r"\s+", " ", texto["contenido"])
    # Espacios al principio y al final
    texto["contenido"] = texto["contenido"].strip()

In [3]:
# Visualización del corpus
for texto in corpus:
    print(f"Grado: {texto['grado']}, Materia: {texto['materia']}")
    print(texto['contenido'][:100] + "...")

Grado: 1er grado, Materia: ciencias_1
exploracion de la naturaleza y la sociedad primer grado indice presentacion conoce tu libro bloque y...
Grado: 1er grado, Materia: civica_1
formacion civica y etica primer grado indice bloque bloque uno dos conoce tu libro me conozco y me c...
Grado: 1er grado, Materia: español_1
espanol libro para el alumno primer grado espanol libro para el alumno primer grado esta obra ilustr...
Grado: 1er grado, Materia: español_2
espanol libro de lectura primer grado quien ha visto las tijeras fernando krahn busca en la bibliote...
Grado: 1er grado, Materia: matematicas_1
desafios matematicos libro para el alumno primer grado desafios matematicos primer grado presentacio...
Grado: 2o grado, Materia: ciencias_2
exploracion de la naturaleza y la sociedad segundo grado indice presentacion conoce tu libro bloque ...
Grado: 2o grado, Materia: civica_2
formacion civica y etica segundo grado indice bloque bloque uno dos presentacion conoce tu libro nin...
Grado: 2o grado, Materia: español_2_1
espanol libro para el alumno segundo grado como utilizar los iconos de tu libro a lo largo de las le...
Grado: 2o grado, Materia: español_2_2
espanol libro de lectura segundo grado indice que te gusta mas por que los perros se huelen los unos...
Grado: 2o grado, Materia: matematicas_2
desafios matematicos libro para el alumno segundo grado indice introduccion bloque comparacion de pr...
Grado: 3er grado, Materia: artistica_3
educacion artistica tercer grado indice presentacion conoce tu libro bloque leccion comencemos el an...
Grado: 3er grado, Materia: ciencias_3
ciencias naturales tercer grado conoce tu libro en este libro se explican algunos fenomenos y proces...
Grado: 3er grado, Materia: civica_3
formacion civica y etica tercer grado conoce tu libro bloque ninas y ninos cuidadosos prevenidos y p...
Grado: 3er grado, Materia: español_3_1
espanol tercer grado espanol conoce tu libro este libro busca proporcionarte muchas oportunidades pa...
Grado: 3er grado, Materia: español_3_2
espanol libro de lectura tercer grado indice el sombrero el pajarraco un pajaro el caracol el pajari...
Grado: 3er grado, Materia: matematicas_3
desafios matematicos libro para el alumno tercer grado indice introduccion bloque los chocolates de ...
Grado: 4o grado, Materia: artistica_4
educacion artistica cuarto grado indice presentacion conoce tu libro leccion leccion leccion leccion...
Grado: 4o grado, Materia: ciencias_4
ciencias naturales cuarto grado conoce tu libro en este libro se explican algunos fenomenos y proces...
Grado: 4o grado, Materia: constitucion_4
conoce nuestra constitucion cuarto grado nombre del alumno a escuela grupo poblacion entidad federat...
Grado: 4o grado, Materia: español_4
espanol libro de lectura cuarto grado indice el colibri el conde olinos el pizarron encantado el tra...
Grado: 4o grado, Materia: historia_4
historia cuarto grado indice conoce tu libro bloque del poblamiento de america al inicio de la agric...
Grado: 4o grado, Materia: matematicas_4
desafios matematicos libro para el alumno cuarto grado indice introduccion bloque los libreros suma ...
Grado: 5o grado, Materia: artistica_5
educacion artistica quinto grado indice presentacion conoce tu libro bloque leccion comencemos el an...
Grado: 5o grado, Materia: ciencias_5
ciencias naturales quinto grado conoce tu libro en este libro se explican algunos fenomenos y proces...
Grado: 5o grado, Materia: espanol_5_1
espanol quinto grado conoce tu libro conoce tu libro este libro busca proporcionarte muchas oportuni...
Grado: 5o grado, Materia: espanol_5_2
espanol libro de lectura quinto grado indice que si que no que todo se acabo serenata huasteca cuadr...
Grado: 5o grado, Materia: historia_5
historia quinto grado indice conoce tu libro bloque los primeros anos de vida independiente panorama...
Grado: 5o grado, Materia: matematicas_5
desafios matematicos libro para el alumno quinto grado indice introduccion bloque cuanto es en total...
Grado: 6o grado, Materia: artistica_6
educacion artistica sexto grado indice leccion leccion leccion leccion leccion leccion leccion lecci...
Grado: 6o grado, Materia: ciencias_6
ciencias naturales sexto grado b o q u e conoce tu libro en este libro se explican algunos fenomenos...
Grado: 6o grado, Materia: civica_6
formacion civica y etica sexto grado presentacion conoce tu libro bloque de la ninez a la adolescenc...
Grado: 6o grado, Materia: espanol_6_1
espanol sexto grado conoce tu libro la asignatura de espanol esta organizada en cinco bloques los cu...
Grado: 6o grado, Materia: espanol_6_2
espanol libro de lectura sexto grado indice el primer beso el sube y baja adios chaparrita las mosca...
Grado: 6o grado, Materia: geografia_6
geografia sexto grado conoce tu libro comencemos en esta seccion identificaras que tanto sabes sobre...
Grado: 6o grado, Materia: historia_6
historia sexto grado indice conoce tu libro bloque la prehistoria de los primeros seres humanos a la...
Grado: 6o grado, Materia: matematicas_6
desafios matematicos libro para el alumno sexto grado indice introduccion bloque los continentes en ...

## Guardar el corpus en diferentes formatos

#### FORMATO JSON

In [4]:
# Formato JSON
import json
# import os

# Si el archivo ya existe, se elimina
if os.path.exists("corpus.json"):
    os.remove("corpus.json")

# Se guarda el corpus en un archivo JSON
with open("corpus.json", "w", encoding="utf-8") as f:
    json.dump(corpus, f, ensure_ascii=False, indent=4)

print("Corpus guardado en corpus.json")

# Filas
print('Cantidad de filas:', len(corpus))
# Columnas
print('Cantidad de columnas:', len(corpus[0]))

Corpus guardado en corpus.json
Cantidad de filas: 36
Cantidad de columnas: 4

In [5]:
# Importar el corpus desde el archivo JSON
import pandas as pd
corpus_json = pd.read_json("corpus.json")

In [6]:
# Encabezado del JSON
corpus_json.head()

,grado,materia,archivo,contenido
0,1er grado,ciencias_1,naturales_1.txt,exploracion de la naturaleza y la sociedad pri...
1,1er grado,civica_1,Civica_1.txt,formacion civica y etica primer grado indice b...
2,1er grado,español_1,espanol_1.txt,espanol libro para el alumno primer grado espa...
3,1er grado,español_2,espanol_2.txt,espanol libro de lectura primer grado quien ha...
4,1er grado,matematicas_1,matematicas_1.txt,desafios matematicos libro para el alumno prim...

In [7]:
# Ahora todos los grados
corpus_json.groupby("grado").count()

           materia  archivo  contenido
grado
1er grado        5        5          5
2o grado         5        5          5
3er grado        6        6          6
4o grado         6        6          6
5o grado         6        6          6
6o grado         8        8          8

In [8]:
# Cuantas filas tiene el corpus
corpus_json.shape

(36, 4)

In [9]:
# Imprimir el json
corpus_json

,grado,materia,archivo,contenido
0,1er grado,ciencias_1,naturales_1.txt,exploracion de la naturaleza y la sociedad pri...
1,1er grado,civica_1,Civica_1.txt,formacion civica y etica primer grado indice b...
2,1er grado,español_1,espanol_1.txt,espanol libro para el alumno primer grado espa...
3,1er grado,español_2,espanol_2.txt,espanol libro de lectura primer grado quien ha...
4,1er grado,matematicas_1,matematicas_1.txt,desafios matematicos libro para el alumno prim...
5,2o grado,ciencias_2,naturales_2.txt,exploracion de la naturaleza y la sociedad seg...
6,2o grado,civica_2,Civica_2.txt,formacion civica y etica segundo grado indice ...
7,2o grado,español_2_1,espanol_2_1.txt,espanol libro para el alumno segundo grado com...
8,2o grado,español_2_2,espanol_2_2.txt,espanol libro de lectura segundo grado indice ...
9,2o grado,matematicas_2,matematicas_2.txt,desafios matematicos libro para el alumno segu...
10,3er grado,artistica_3,artistica_3.txt,educacion artistica tercer grado indice presen...
11,3er grado,ciencias_3,ciencias_3.txt,ciencias naturales tercer grado conoce tu libr...
12,3er grado,civica_3,civica_3.txt,formacion civica y etica tercer grado conoce t...
13,3er grado,español_3_1,espanol_3_1.txt,espanol tercer grado espanol conoce tu libro e...
14,3er grado,español_3_2,espanol_3_2.txt,espanol libro de lectura tercer grado indice e...
15,3er grado,matematicas_3,matematicas_3.txt,desafios matematicos libro para el alumno terc...
16,4o grado,artistica_4,artistica_4.txt,educacion artistica cuarto grado indice presen...
17,4o grado,ciencias_4,naturales_4.txt,ciencias naturales cuarto grado conoce tu libr...
18,4o grado,constitucion_4,constitucion_4.txt,conoce nuestra constitucion cuarto grado nombr...
19,4o grado,español_4,espanol_4.txt,espanol libro de lectura cuarto grado indice e...
20,4o grado,historia_4,historia_4.txt,historia cuarto grado indice conoce tu libro b...
21,4o grado,matematicas_4,matematicas_4.txt,desafios matematicos libro para el alumno cuar...
22,5o grado,artistica_5,artistica_5.txt,educacion artistica quinto grado indice presen...
23,5o grado,ciencias_5,naturales_5.txt,ciencias naturales quinto grado conoce tu libr...
24,5o grado,espanol_5_1,espanol_5_1.txt,espanol quinto grado conoce tu libro conoce tu...
25,5o grado,espanol_5_2,espanol_5_2.txt,espanol libro de lectura quinto grado indice q...
26,5o grado,historia_5,historia_5.txt,historia quinto grado indice conoce tu libro b...
27,5o grado,matematicas_5,matematicas_5.txt,desafios matematicos libro para el alumno quin...
28,6o grado,artistica_6,artistica_6.txt,educacion artistica sexto grado indice leccion...
29,6o grado,ciencias_6,naturales_6.txt,ciencias naturales sexto grado b o q u e conoc...
30,6o grado,civica_6,civica_6.txt,formacion civica y etica sexto grado presentac...
31,6o grado,espanol_6_1,espanol_6_1.txt,espanol sexto grado conoce tu libro la asignat...
32,6o grado,espanol_6_2,espanol_6_2.txt,espanol libro de lectura sexto grado indice el...
33,6o grado,geografia_6,geografia_6.txt,geografia sexto grado conoce tu libro comencem...
34,6o grado,historia_6,historia_6.txt,historia sexto grado indice conoce tu libro bl...
35,6o grado,matematicas_6,matematicas_6.txt,desafios matematicos libro para el alumno sext...

#### FORMATO CSV

In [10]:
# Transformar el formato JSON a CSV
# import json

# Cargar el corpus desde el archivo JSON
with open("corpus.json", "r", encoding="utf-8") as f:
    corpus = json.load(f)

# Guardar el corpus en un archivo CSV
import csv

# Si el archivo ya existe, se elimina
if os.path.exists("corpus.csv"):
    os.remove("corpus.csv")

with open("corpus.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["grado", "materia", "archivo", "contenido"])
    for texto in corpus:
        contenido = texto["contenido"].replace("\n", " ").replace("\r", " ").replace('"', '""')
        writer.writerow([
            texto["grado"],
            texto["materia"],
            texto["archivo"],
            f'"{contenido}"'
        ])
        
print("Corpus guardado en corpus.csv")

# Filas
print('Cantidad de filas:', len(corpus))
# Columnas
print('Cantidad de columnas:', len(corpus[0]))

Corpus guardado en corpus.csv
Cantidad de filas: 36
Cantidad de columnas: 4

In [11]:
# Imprimir el csv
import pandas as pd
corpus_csv = pd.read_csv("corpus.csv")

In [12]:
# Encabezado del CSV
corpus_csv.head()

,grado,materia,archivo,contenido
0,1er grado,ciencias_1,naturales_1.txt,"""exploracion de la naturaleza y la sociedad pr..."
1,1er grado,civica_1,Civica_1.txt,"""formacion civica y etica primer grado indice ..."
2,1er grado,español_1,espanol_1.txt,"""espanol libro para el alumno primer grado esp..."
3,1er grado,español_2,espanol_2.txt,"""espanol libro de lectura primer grado quien h..."
4,1er grado,matematicas_1,matematicas_1.txt,"""desafios matematicos libro para el alumno pri..."

In [13]:
# Ahora todos los grados
corpus_csv.groupby("grado").count()

           materia  archivo  contenido
grado
1er grado        5        5          5
2o grado         5        5          5
3er grado        6        6          6
4o grado         6        6          6
5o grado         6        6          6
6o grado         8        8          8

In [14]:
# Cuantas filas tiene el corpus
corpus_csv.shape

(36, 4)

In [15]:
# Imprimir el csv
corpus_csv

,grado,materia,archivo,contenido
0,1er grado,ciencias_1,naturales_1.txt,"""exploracion de la naturaleza y la sociedad pr..."
1,1er grado,civica_1,Civica_1.txt,"""formacion civica y etica primer grado indice ..."
2,1er grado,español_1,espanol_1.txt,"""espanol libro para el alumno primer grado esp..."
3,1er grado,español_2,espanol_2.txt,"""espanol libro de lectura primer grado quien h..."
4,1er grado,matematicas_1,matematicas_1.txt,"""desafios matematicos libro para el alumno pri..."
5,2o grado,ciencias_2,naturales_2.txt,"""exploracion de la naturaleza y la sociedad se..."
6,2o grado,civica_2,Civica_2.txt,"""formacion civica y etica segundo grado indice..."
7,2o grado,español_2_1,espanol_2_1.txt,"""espanol libro para el alumno segundo grado co..."
8,2o grado,español_2_2,espanol_2_2.txt,"""espanol libro de lectura segundo grado indice..."
9,2o grado,matematicas_2,matematicas_2.txt,"""desafios matematicos libro para el alumno seg..."
10,3er grado,artistica_3,artistica_3.txt,"""educacion artistica tercer grado indice prese..."
11,3er grado,ciencias_3,ciencias_3.txt,"""ciencias naturales tercer grado conoce tu lib..."
12,3er grado,civica_3,civica_3.txt,"""formacion civica y etica tercer grado conoce ..."
13,3er grado,español_3_1,espanol_3_1.txt,"""espanol tercer grado espanol conoce tu libro ..."
14,3er grado,español_3_2,espanol_3_2.txt,"""espanol libro de lectura tercer grado indice ..."
15,3er grado,matematicas_3,matematicas_3.txt,"""desafios matematicos libro para el alumno ter..."
16,4o grado,artistica_4,artistica_4.txt,"""educacion artistica cuarto grado indice prese..."
17,4o grado,ciencias_4,naturales_4.txt,"""ciencias naturales cuarto grado conoce tu lib..."
18,4o grado,constitucion_4,constitucion_4.txt,"""conoce nuestra constitucion cuarto grado nomb..."
19,4o grado,español_4,espanol_4.txt,"""espanol libro de lectura cuarto grado indice ..."
20,4o grado,historia_4,historia_4.txt,"""historia cuarto grado indice conoce tu libro ..."
21,4o grado,matematicas_4,matematicas_4.txt,"""desafios matematicos libro para el alumno cua..."
22,5o grado,artistica_5,artistica_5.txt,"""educacion artistica quinto grado indice prese..."
23,5o grado,ciencias_5,naturales_5.txt,"""ciencias naturales quinto grado conoce tu lib..."
24,5o grado,espanol_5_1,espanol_5_1.txt,"""espanol quinto grado conoce tu libro conoce t..."
25,5o grado,espanol_5_2,espanol_5_2.txt,"""espanol libro de lectura quinto grado indice ..."
26,5o grado,historia_5,historia_5.txt,"""historia quinto grado indice conoce tu libro ..."
27,5o grado,matematicas_5,matematicas_5.txt,"""desafios matematicos libro para el alumno qui..."
28,6o grado,artistica_6,artistica_6.txt,"""educacion artistica sexto grado indice leccio..."
29,6o grado,ciencias_6,naturales_6.txt,"""ciencias naturales sexto grado b o q u e cono..."
30,6o grado,civica_6,civica_6.txt,"""formacion civica y etica sexto grado presenta..."
31,6o grado,espanol_6_1,espanol_6_1.txt,"""espanol sexto grado conoce tu libro la asigna..."
32,6o grado,espanol_6_2,espanol_6_2.txt,"""espanol libro de lectura sexto grado indice e..."
33,6o grado,geografia_6,geografia_6.txt,"""geografia sexto grado conoce tu libro comence..."
34,6o grado,historia_6,historia_6.txt,"""historia sexto grado indice conoce tu libro b..."
35,6o grado,matematicas_6,matematicas_6.txt,"""desafios matematicos libro para el alumno sex..."